### ISSUE TITLE
F-Droid avalability

### ISSUE THREAD

**Issue by B4rc1** [AdrianMiozga/GetFlow#1]
Hey I found this app in G-Droid, an unofficial f-droid client, but it crashed when I try to install it.
I went to investigate. I can search for GetFlow on my desktop Computer just fine:

![grafik](https://user-images.githubusercontent.com/10383737/103225830-17674f80-492b-11eb-8815-f8e279feec56.png)

https://search.f-droid.org/?q=getflow

But when I click on the search result I just get a 404:

https://f-droid.org/packages/org.wentura.getflow

The Official F-Droid App does not even list GetFlow.
I don't know much about F-Droids organisation and am not even sure this is the right place to report the issue but I found this in the f-droid/data repo:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.wentura.getflow.yml

So to me it looks like everything SHOULD be working. I would really like to try out this app, but don't want to go through the hassle of building and signing it myself.

**Comment by H4TIEL** [comment]
Hey you can download the apk from [https://fossdroid.com/a/getflow.apk](fossdroid)

**Comment by B4rc1** [comment]
Thanks @H4TIEL that works!
Also the F-Droid Issue seems to have fixed itself, as I can now download it through F-Droid and no longer get a 404.
