### ISSUE TITLE
Unable to quit app

### ISSUE THREAD

**Issue by lordfolken** [AdrianMiozga/GetFlow#5]
Hello, 

First of all: kick-ass app. :)

I'd like to exit the app at the end of the workday. The notification seems to stick and i'm unable to clear the notification or quit and exit the app. The only way to terminate, is to go into the app menu and force-quit the app. 

Would it be possible to exit the app, via, for example an exit option in the menu?

**Comment by AdrianMiozga** [comment]
What exactly happens when you press Stop button inside notification? Does the timer keep going? Is it the same when you long-press the timer inside of application?

**Comment by lordfolken** [comment]
There is unfortunately no stop button inside the notification. It says "break time!" and that's it. Its not dismiss-able, and there is no option, other than suppressing it entirely. It also keeps vibrating no matter what i do.

**Comment by AdrianMiozga** [comment]
Anytime you want to stop current session, you can press the timer for about one second. In the same manner, you can tap it to start/pause or swipe from right to left to skip current session.

This also applies when work timer ends and “Break time!” notification pops up. In that case, the timer should have breathing animation (fade-in and out).

If you still have problems, let me know. Another less intended way would be to start another work session and stop it from notification button. Sessions under 30 seconds aren’t saved anywhere.

If you don’t have three buttons under notification (pause, skip, stop) when the timer is running, then that’s another issue.

**Comment by lordfolken** [comment]
I think this is no longer an issue. My current droid shows the stop button in the notification.
